In [1]:
import pandas as py
import numpy  as np
from sklearn import linear_model
import matplotlib.pyplot as plt


In [2]:
df = py.read_csv("homeprices.csv")
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [3]:
# price = m1* area + m2+bedrooms + m3*age + b
# Price - Dependent Variable
# area, bedroom, age are Independent variables (features) 
# m1, m2, m3 - coefficient
# b - intercept

In [4]:
# Replace NaN with median value
# taking median is safe assumption
import math
median_bedrooms = df.bedroom.median()
median_bedrooms = math.floor(median_bedrooms)
median_bedrooms


3

In [5]:
# panda function fillna to fill null with median number
df.bedroom = df.bedroom.fillna(median_bedrooms)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [6]:
#CREATE LINEAR MODEL
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']], df.price)
# reg.fit (Area, bedroom, age are - Indipendent variable, Price = Target Variable)

LinearRegression()

In [7]:
reg.coef_
# m1, m2, m3 - coefficient m1 = area, m2 = bedroom, m3 = age 

array([   137.25, -26025.  ,  -6825.  ])

In [8]:
reg.intercept_

383724.9999999998

In [9]:
#3000 sq ft area, 3 bedrooms , 40 year old
#2500 sqr ft area, 4 bedrooms, 5 year old
reg.predict([[3000, 3, 40]])

array([444400.])

In [10]:
reg.predict([[2500, 4, 5]])

array([588625.])

In [14]:
# price = m1* area + m2+bedrooms + m3*age + b
137.25*3000 +   -26025 * 3 + -6825* 40 + 83724.9999999998

144399.9999999998