In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a.ndim

1

In [4]:
b = np.arange(100)

In [5]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
b.ndim

1

In [7]:
b.dtype

dtype('int32')

In [8]:
b.itemsize

4

In [10]:
a = np.array([[1,2],[2,3],[5,4]], dtype=np.float64)

a.itemsize

In [11]:
a.itemsize

8

In [12]:
a

array([[1., 2.],
       [2., 3.],
       [5., 4.]])

In [14]:
#Total Elements
a.size

6

In [17]:
a = np.zeros((5,6))

In [18]:
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
np.arange(1,5,0.001)

array([1.   , 1.001, 1.002, ..., 4.997, 4.998, 4.999])

In [25]:
#Random number from list
a = np.linspace(1,5,10)

In [26]:
a.shape

(10,)

In [32]:
b = a.reshape(5,2)

In [33]:
b

array([[1.        , 1.44444444],
       [1.88888889, 2.33333333],
       [2.77777778, 3.22222222],
       [3.66666667, 4.11111111],
       [4.55555556, 5.        ]])

In [35]:
a.min()

1.0

In [36]:
a.max()

5.0

In [37]:
a.sum()

30.0

In [45]:
#ColumnWise TOtal
b.sum(axis=0)

array([13.88888889, 16.11111111])

In [46]:
#rowwise Total
b.sum(axis=1)

array([2.44444444, 4.22222222, 6.        , 7.77777778, 9.55555556])

In [47]:
#sqrt
np.sqrt(b)

array([[1.        , 1.20185043],
       [1.37436854, 1.52752523],
       [1.66666667, 1.79505494],
       [1.91485422, 2.02758751],
       [2.13437475, 2.23606798]])

In [48]:
np.std(b)

1.2765694770084506

In [50]:
a1 = np.array([[1,2],[3,4]])
b1 = np.array([[5,6],[7,8]])

In [51]:
a1 + b1

array([[ 6,  8],
       [10, 12]])

In [52]:
a1 > b1

array([[False, False],
       [False, False]])

In [56]:
b1 > a1

array([[False, False],
       [False, False]])

In [57]:
 a1 * b1 

array([[25, 36],
       [49, 64]])

In [58]:
np.std(a1*b1)

14.568802284333465